### 메인 계좌 충전
POST http://localhost:8080/api/v1/account/checking/charge
Content-Type: application/json

{
  "accountNumber": "8888-74-8607575",
  "amount": 5000
}

### 적금 계좌 생성
POST http://localhost:8080/api/v1/account/saving
Content-Type: application/json

{
  "memberId": 1
}

### 적금 계좌 납입
POST http://localhost:8080/api/v1/account/saving/payin
Content-Type: application/json

{
  "savingAccountNumber": "8800-01-2180123",
  "checkingAccountNumber": "8888-30-2104037",
  "amount": 5000
}

### 친구 계좌로 송금
POST http://localhost:8080/api/v1/account/checking/remit
Content-Type: application/json

{
  "myAccountNumber": "8888-60-8082444",
  "receiverAccountNumber": "8888-44-8427001",
  "amount": 24000
}