### 친구 계좌로 송금
POST http://localhost:8080/api/v1/transactions/remit
Content-Type: application/json

{
  "senderAccountNumber": "8888-60-8082444",
  "receiverAccountNumber": "8888-44-8427001",
  "amount": 24000
}